/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 -t --root public/ --transform ./public/models/compost_bags_4k.gltf/compost_bags_4k.gltf
Files: ./public/models/compost_bags_4k.gltf/compost_bags_4k.gltf [11.31KB] > /home/sou/src/visualizers/compost_bags_4k-transformed.glb [667.4KB] (-5801%)
*/

import { /* useAnimations, */ useGLTF } from "@react-three/drei"
import type { ThreeElements } from "@react-three/fiber"
import { useRef } from "react"
import type * as THREE from "three"
import type { GLTF } from "three-stdlib"

type ActionName = "compost_bags_leaning" | "compost_bags_floor"

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}

type GLTFResult = GLTF & {
  nodes: {
    compost_bags_floorstacked: THREE.Mesh
    compost_bags_leaning: THREE.Mesh
    compost_bags_floor: THREE.Mesh
  }
  materials: {
    compost_bags: THREE.MeshPhysicalMaterial
  }
  animations: GLTFAction[]
}

export function CompostBags(props: ThreeElements["group"]) {
  const group = useRef<THREE.Group>(null)
  const { nodes, materials /* animations */ } = useGLTF(
    "/models/compost_bags_4k-transformed.glb",
  ) as unknown as GLTFResult
  // const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh
          name="compost_bags_floorstacked"
          geometry={nodes.compost_bags_floorstacked.geometry}
          material={materials.compost_bags}
          position={[-0.396, 0.07, 0]}
        />
        <mesh
          name="compost_bags_leaning"
          geometry={nodes.compost_bags_leaning.geometry}
          material={materials.compost_bags}
          position={[0.699, 0, 0.077]}
          rotation={[1.509, 0.142, -1.16]}
        />
        <mesh
          name="compost_bags_floor"
          geometry={nodes.compost_bags_floor.geometry}
          material={materials.compost_bags}
          position={[-0.396, 0, 0]}
          rotation={[0.052, 0, 0]}
        />
      </group>
    </group>
  )
}

// useGLTF.preload("/models/compost_bags_4k-transformed.glb")
