/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 -t --root public/ --transform public/models/marble_bust_01_4k.gltf/marble_bust_01_4k.gltf
Files: public/models/marble_bust_01_4k.gltf/marble_bust_01_4k.gltf [2.79KB] > /home/sou/src/visualizers/marble_bust_01_4k-transformed.glb [603.41KB] (-21528%)
*/

import { useGLTF } from "@react-three/drei"
import type { ThreeElements } from "@react-three/fiber"
import type * as THREE from "three"
import type { GLTF } from "three-stdlib"

type GLTFResult = GLTF & {
  nodes: {
    marble_bust_01: THREE.Mesh
  }
  materials: {
    marble_bust_01: THREE.MeshStandardMaterial
  }
}

export function MarbleBust(props: ThreeElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/models/marble_bust_01_4k-transformed.glb",
  ) as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.marble_bust_01.geometry}
        material={materials.marble_bust_01}
        position={[0, 0.028, 0]}
      />
    </group>
  )
}

// useGLTF.preload("/models/marble_bust_01_4k-transformed.glb")
