/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 -t --root public/ --transform ./public/models/plastic_monobloc_chair_01_4k.gltf/plastic_monobloc_chair_01_4k.gltf
Files: ./public/models/plastic_monobloc_chair_01_4k.gltf/plastic_monobloc_chair_01_4k.gltf [2.89KB] > /home/sou/src/visualizers/plastic_monobloc_chair_01_4k-transformed.glb [598.52KB] (-20610%)
*/

import { useGLTF } from "@react-three/drei"
import type { ThreeElements } from "@react-three/fiber"
import type * as THREE from "three"
import type { GLTF } from "three-stdlib"

type GLTFResult = GLTF & {
  nodes: {
    plastic_monobloc_chair_01: THREE.Mesh
  }
  materials: {
    plastic_monobloc_chair_01: THREE.MeshStandardMaterial
  }
}

export function PlasticMonoblocChair(props: ThreeElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/models/plastic_monobloc_chair_01_4k-transformed.glb",
  ) as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.plastic_monobloc_chair_01.geometry}
        material={materials.plastic_monobloc_chair_01}
      />
    </group>
  )
}

// useGLTF.preload("/models/plastic_monobloc_chair_01_4k-transformed.glb")
