/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 -t --root public/ --transform ./public/models/potted_plant_04_4k.gltf/potted_plant_04_4k.gltf
Files: ./public/models/potted_plant_04_4k.gltf/potted_plant_04_4k.gltf [7.08KB] > /home/sou/src/visualizers/potted_plant_04_4k-transformed.glb [949.64KB] (-13313%)
*/

import { useGLTF } from "@react-three/drei"
import type { ThreeElements } from "@react-three/fiber"
import type * as THREE from "three"
import type { GLTF } from "three-stdlib"

type GLTFResult = GLTF & {
  nodes: {
    potted_plant_04_ground: THREE.Mesh
  }
  materials: {
    potted_plant_04: THREE.MeshStandardMaterial
  }
}

export function PottedPlant4(props: ThreeElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/models/potted_plant_04_4k-transformed.glb",
  ) as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.potted_plant_04_ground.geometry} material={materials.potted_plant_04} />
    </group>
  )
}

// useGLTF.preload("/models/potted_plant_04_4k-transformed.glb")
