/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 -t --root public/ --transform ./public/models/potted_plant_02_4k.gltf/potted_plant_02_4k.gltf
Files: ./public/models/potted_plant_02_4k.gltf/potted_plant_02_4k.gltf [6.65KB] > /home/sou/src/visualizers/potted_plant_02_4k-transformed.glb [1.31MB] (-19549%)
*/

import { useGLTF } from "@react-three/drei"
import type { ThreeElements } from "@react-three/fiber"
import type * as THREE from "three"
import type { GLTF } from "three-stdlib"

type GLTFResult = GLTF & {
  nodes: {
    potted_plant_02_pot: THREE.Mesh
    potted_plant_02_leaves: THREE.Mesh
  }
  materials: {
    potted_plant_02_pot: THREE.MeshStandardMaterial
    potted_plant_02_leaves: THREE.MeshStandardMaterial
  }
}

export function PottedPlant2(props: ThreeElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/models/potted_plant_02_4k-transformed.glb",
  ) as unknown as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.potted_plant_02_pot.geometry}
        material={materials.potted_plant_02_pot}
      />
      <mesh
        geometry={nodes.potted_plant_02_leaves.geometry}
        material={materials.potted_plant_02_leaves}
        position={[-0.003, 0.305, 0.001]}
      />
    </group>
  )
}

// useGLTF.preload("/models/potted_plant_02_4k-transformed.glb")
