/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 -t --root public/ --transform ./public/models/shrub_sorrel_01_4k.gltf/shrub_sorrel_01_4k.gltf
Files: ./public/models/shrub_sorrel_01_4k.gltf/shrub_sorrel_01_4k.gltf [17.43KB] > /home/sou/src/visualizers/shrub_sorrel_01_4k-transformed.glb [460.28KB] (-2541%)
*/

import { useGLTF } from "@react-three/drei"
import type { ThreeElements } from "@react-three/fiber"
import type * as THREE from "three"
import type { GLTF } from "three-stdlib"

type GLTFResult = GLTF & {
  nodes: {
    shrub_sorrel_01_k: THREE.Mesh
  }
  materials: {
    shrub_sorrel_01: THREE.MeshStandardMaterial
  }
}

export function ShrubSorrel1(props: ThreeElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/models/shrub_sorrel_01_4k-transformed.glb",
  ) as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.shrub_sorrel_01_k.geometry}
        material={materials.shrub_sorrel_01}
        position={[0.097, 0, -0.003]}
      />
    </group>
  )
}

// useGLTF.preload("/models/shrub_sorrel_01_4k-transformed.glb")
