/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 -t --root public/ --transform ./public/models/stone_tiles_03_4k.gltf/stone_tiles_03_4k.gltf
Files: ./public/models/stone_tiles_03_4k.gltf/stone_tiles_03_4k.gltf [2.8KB] > /home/sou/src/visualizers/stone_tiles_03_4k-transformed.glb [1.96MB] (-70016%)
*/

import { useGLTF } from "@react-three/drei"
import type { ThreeElements } from "@react-three/fiber"
import type * as THREE from "three"
import type { GLTF } from "three-stdlib"

type GLTFResult = GLTF & {
  nodes: {
    sphere_gltf: THREE.Mesh
  }
  materials: {
    stone_tiles_03: THREE.MeshStandardMaterial
  }
}

export function StoneTiles3(props: ThreeElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/models/stone_tiles_03_4k-transformed.glb",
  ) as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.sphere_gltf.geometry} material={materials.stone_tiles_03} />
    </group>
  )
}

// useGLTF.preload("/models/stone_tiles_03_4k-transformed.glb")
