/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 -t --root public/ --transform ./public/models/island_tree_01_4k.gltf/island_tree_01_4k.gltf
Files: ./public/models/island_tree_01_4k.gltf/island_tree_01_4k.gltf [8.58KB] > /home/sou/src/visualizers/island_tree_01_4k-transformed.glb [10.63MB] (-123808%)
*/

import { useGLTF } from "@react-three/drei"
import type { ThreeElements } from "@react-three/fiber"
import type * as THREE from "three"
import type { GLTF } from "three-stdlib"

type GLTFResult = GLTF & {
  nodes: {
    island_trees_01_blockout_cleaned: THREE.Mesh
    island_trees_01_blockout_cleaned_1: THREE.Mesh
    island_trees_01_blockout_cleaned_2: THREE.Mesh
  }
  materials: {
    island_tree_01: THREE.MeshStandardMaterial
    island_tree_01_leaves: THREE.MeshStandardMaterial
    island_tree_01_branches: THREE.MeshStandardMaterial
  }
}

export function Tree(props: ThreeElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/models/island_tree_01_4k-transformed.glb",
  ) as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.island_trees_01_blockout_cleaned.geometry}
        material={materials.island_tree_01}
      />
      <mesh
        geometry={nodes.island_trees_01_blockout_cleaned_1.geometry}
        material={materials.island_tree_01_leaves}
      />
      <mesh
        geometry={nodes.island_trees_01_blockout_cleaned_2.geometry}
        material={materials.island_tree_01_branches}
      />
    </group>
  )
}

// useGLTF.preload("/models/island_tree_01_4k-transformed.glb")
