/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 -t --root public/ --transform public/models/watering_can_metal_01_4k.gltf/watering_can_metal_01_4k.gltf
Files: public/models/watering_can_metal_01_4k.gltf/watering_can_metal_01_4k.gltf [3.18KB] > /home/sou/src/visualizers/watering_can_metal_01_4k-transformed.glb [964.56KB] (-30232%)
*/

import { useGLTF } from "@react-three/drei"
import type { ThreeElements } from "@react-three/fiber"
import type * as THREE from "three"
import type { GLTF } from "three-stdlib"

type GLTFResult = GLTF & {
  nodes: {
    watering_can_metal_01: THREE.Mesh
  }
  materials: {
    watering_can_metal_01: THREE.MeshStandardMaterial
  }
}

export function WateringCanMetal(props: ThreeElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/models/watering_can_metal_01_4k-transformed.glb",
  ) as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.watering_can_metal_01.geometry}
        material={materials.watering_can_metal_01}
      />
    </group>
  )
}

// useGLTF.preload("/models/watering_can_metal_01_4k-transformed.glb")
