/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 -t --root public/ --transform ./public/models/folding_wooden_stool_4k.gltf/folding_wooden_stool_4k.gltf
Files: ./public/models/folding_wooden_stool_4k.gltf/folding_wooden_stool_4k.gltf [2.84KB] > /home/sou/src/visualizers/folding_wooden_stool_4k-transformed.glb [907.42KB] (-31851%)
*/

import { useGLTF } from "@react-three/drei"
import type { ThreeElements } from "@react-three/fiber"
import type * as THREE from "three"
import type { GLTF } from "three-stdlib"

type GLTFResult = GLTF & {
  nodes: {
    folding_wooden_stool: THREE.Mesh
  }
  materials: {
    folding_wooden_stool: THREE.MeshStandardMaterial
  }
}

export function WoodenStool(props: ThreeElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/models/folding_wooden_stool_4k-transformed.glb",
  ) as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.folding_wooden_stool.geometry}
        material={materials.folding_wooden_stool}
      />
    </group>
  )
}

// useGLTF.preload("/models/folding_wooden_stool_4k-transformed.glb")
